version: '2'

services:
  elasticsearch:
    image: elasticsearch:7.8.0
    restart: always
    ports:
    - "9200:9200"
    - "9300:9300"
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    volumes:
    - "./elasticsearch/data:/usr/share/elasticsearch/data"
  kibana:
    image: kibana:7.8.0
    restart: always
    ports:
    - "5601:5601"
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
    - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
  logstash:
    image: logstash:7.8.0
    restart: always
    ports:
    - "5044:5044"
    - "9600:9600"
    depends_on:
      - elasticsearch
      - kibana
    volumes:
    - "./logstash/config/:/usr/share/logstash/conf.d/"
    - "./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml"
    container_name: logstash